"""add resume analysis

Revision ID: 44305a228525
Revises: 38746bea97e5
Create Date: 2026-09-23 10:21:52.060322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44305a228525'
down_revision: Union[str, Sequence[str], None] = '38746bea97e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis')
    # ### end Alembic commands ###
