"""update career profile model

Revision ID: a8fd0cefc901
Revises: 
Create Date: 2026-09-04 01:59:01.861548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fd0cefc901'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('career_profiles', sa.Column('projects', sa.Text(), nullable=False))
    op.add_column('career_profiles', sa.Column('years_experience', sa.Float(), nullable=False))
    op.alter_column('career_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('career_profiles', 'education',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('career_profiles', 'skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('career_profiles', 'experience',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('career_profiles', 'target_role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('career_profiles', 'target_role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('career_profiles', 'experience',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('career_profiles', 'skills',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('career_profiles', 'education',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('career_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('career_profiles', 'years_experience')
    op.drop_column('career_profiles', 'projects')
    op.drop_column('career_profiles', 'name')
    # ### end Alembic commands ###
