"""add career goal to career profiles

Revision ID: cec1e6130712
Revises: 44305a228525
Create Date: 2026-10-03 16:04:12.456611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec1e6130712'
down_revision: Union[str, Sequence[str], None] = '44305a228525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('career_goal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'career_goal')
    # ### end Alembic commands ###
